//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imed.LicenciasMedicas
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:WsLMEEmp", ConfigurationName = "Imed.LicenciasMedicas.WsLMEEmpPortType")]
    public interface WsLMEEmpPortType
    {

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEDetLccZAResponse1> LMEDetLccZAAsync(Imed.LicenciasMedicas.LMEDetLccZARequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEEvenLccResponse1> LMEEvenLccAsync(Imed.LicenciasMedicas.LMEEvenLccRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEInfSeccCResponse1> LMEInfSeccCAsync(Imed.LicenciasMedicas.LMEInfSeccCRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEInfAdjuntoResponse1> LMEInfAdjuntoAsync(Imed.LicenciasMedicas.LMEInfAdjuntoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEVerPronunciamientoResponse1> LMEVerPronunciamientoAsync(Imed.LicenciasMedicas.LMEVerPronunciamientoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEEstLccResponse1> LMEEstLccAsync(Imed.LicenciasMedicas.LMEEstLccRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEDettLccPdfResponse> LMEDettLccPdfAsync(Imed.LicenciasMedicas.LMEDettLccPdfRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEDetLccZA
    {

        private string codigoOperadorField;

        private int rutEmpleadorField;

        private string dvEmpleadorField;

        private string idUnidadrrhhField;

        private string claveField;

        private int numLicenciaField;

        private string digLicenciaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CodigoOperador
        {
            get
            {
                return this.codigoOperadorField;
            }
            set
            {
                this.codigoOperadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 1)]
        public int RutEmpleador
        {
            get
            {
                return this.rutEmpleadorField;
            }
            set
            {
                this.rutEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string DvEmpleador
        {
            get
            {
                return this.dvEmpleadorField;
            }
            set
            {
                this.dvEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string IdUnidadrrhh
        {
            get
            {
                return this.idUnidadrrhhField;
            }
            set
            {
                this.idUnidadrrhhField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 5)]
        public int NumLicencia
        {
            get
            {
                return this.numLicenciaField;
            }
            set
            {
                this.numLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string DigLicencia
        {
            get
            {
                return this.digLicenciaField;
            }
            set
            {
                this.digLicenciaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEDetLccPdfResponse
    {

        private string estadoField;

        private string gloEstadoField;

        private byte[] dctoLmeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 0)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string GloEstado
        {
            get
            {
                return this.gloEstadoField;
            }
            set
            {
                this.gloEstadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 2)]
        public byte[] DctoLme
        {
            get
            {
                return this.dctoLmeField;
            }
            set
            {
                this.dctoLmeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEDettLccPdf
    {

        private string codigoOperadorField;

        private string rutEmpleadorField;

        private string dvEmpleadorField;

        private string idUnidadrrhhField;

        private string claveField;

        private string numLicenciaField;

        private string digLicenciaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CodigoOperador
        {
            get
            {
                return this.codigoOperadorField;
            }
            set
            {
                this.codigoOperadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 1)]
        public string RutEmpleador
        {
            get
            {
                return this.rutEmpleadorField;
            }
            set
            {
                this.rutEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string DvEmpleador
        {
            get
            {
                return this.dvEmpleadorField;
            }
            set
            {
                this.dvEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string IdUnidadrrhh
        {
            get
            {
                return this.idUnidadrrhhField;
            }
            set
            {
                this.idUnidadrrhhField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 5)]
        public string NumLicencia
        {
            get
            {
                return this.numLicenciaField;
            }
            set
            {
                this.numLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string DigLicencia
        {
            get
            {
                return this.digLicenciaField;
            }
            set
            {
                this.digLicenciaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class EstadoLicencia
    {

        private string codEstadoField;

        private string glosaEstadoField;

        private string observacionField;

        private System.DateTime fechaField;

        private System.DateTime fechaHoraField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 0)]
        public string CodEstado
        {
            get
            {
                return this.codEstadoField;
            }
            set
            {
                this.codEstadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string GlosaEstado
        {
            get
            {
                return this.glosaEstadoField;
            }
            set
            {
                this.glosaEstadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 3)]
        public System.DateTime Fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public System.DateTime FechaHora
        {
            get
            {
                return this.fechaHoraField;
            }
            set
            {
                this.fechaHoraField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEEstLccResponse
    {

        private string estadoField;

        private string gloEstadoField;

        private EstadoLicencia[] listaEstadosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 0)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string GloEstado
        {
            get
            {
                return this.gloEstadoField;
            }
            set
            {
                this.gloEstadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public EstadoLicencia[] ListaEstados
        {
            get
            {
                return this.listaEstadosField;
            }
            set
            {
                this.listaEstadosField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEEstLcc
    {

        private string codigoOperadorField;

        private string rutEmpleadorField;

        private string dvEmpleadorField;

        private string idUnidadrrhhField;

        private string claveField;

        private string numLicenciaField;

        private string dvLicenciaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CodigoOperador
        {
            get
            {
                return this.codigoOperadorField;
            }
            set
            {
                this.codigoOperadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 1)]
        public string RutEmpleador
        {
            get
            {
                return this.rutEmpleadorField;
            }
            set
            {
                this.rutEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string DvEmpleador
        {
            get
            {
                return this.dvEmpleadorField;
            }
            set
            {
                this.dvEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string IdUnidadrrhh
        {
            get
            {
                return this.idUnidadrrhhField;
            }
            set
            {
                this.idUnidadrrhhField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 5)]
        public string NumLicencia
        {
            get
            {
                return this.numLicenciaField;
            }
            set
            {
                this.numLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string DvLicencia
        {
            get
            {
                return this.dvLicenciaField;
            }
            set
            {
                this.dvLicenciaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LiquidacionType
    {

        private string tipoLiquidacionField;

        private string monto_aporte_pensionesField;

        private string monto_aporte_saludField;

        private string monto_seguro_CesantiaField;

        private string monto_apagar_subsidioField;

        private System.DateTime fecha_desde_liquidacionField;

        private bool fecha_desde_liquidacionFieldSpecified;

        private System.DateTime fecha_hasta_liquidacionField;

        private bool fecha_hasta_liquidacionFieldSpecified;

        private System.DateTime fecha_pago_probableField;

        private bool fecha_pago_probableFieldSpecified;

        private string ndias_apagar_subsidiosField;

        private string ndias_apagar_previsionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 0)]
        public string TipoLiquidacion
        {
            get
            {
                return this.tipoLiquidacionField;
            }
            set
            {
                this.tipoLiquidacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 1)]
        public string monto_aporte_pensiones
        {
            get
            {
                return this.monto_aporte_pensionesField;
            }
            set
            {
                this.monto_aporte_pensionesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 2)]
        public string monto_aporte_salud
        {
            get
            {
                return this.monto_aporte_saludField;
            }
            set
            {
                this.monto_aporte_saludField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 3)]
        public string monto_seguro_Cesantia
        {
            get
            {
                return this.monto_seguro_CesantiaField;
            }
            set
            {
                this.monto_seguro_CesantiaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 4)]
        public string monto_apagar_subsidio
        {
            get
            {
                return this.monto_apagar_subsidioField;
            }
            set
            {
                this.monto_apagar_subsidioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public System.DateTime fecha_desde_liquidacion
        {
            get
            {
                return this.fecha_desde_liquidacionField;
            }
            set
            {
                this.fecha_desde_liquidacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_desde_liquidacionSpecified
        {
            get
            {
                return this.fecha_desde_liquidacionFieldSpecified;
            }
            set
            {
                this.fecha_desde_liquidacionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public System.DateTime fecha_hasta_liquidacion
        {
            get
            {
                return this.fecha_hasta_liquidacionField;
            }
            set
            {
                this.fecha_hasta_liquidacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_hasta_liquidacionSpecified
        {
            get
            {
                return this.fecha_hasta_liquidacionFieldSpecified;
            }
            set
            {
                this.fecha_hasta_liquidacionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public System.DateTime fecha_pago_probable
        {
            get
            {
                return this.fecha_pago_probableField;
            }
            set
            {
                this.fecha_pago_probableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_pago_probableSpecified
        {
            get
            {
                return this.fecha_pago_probableFieldSpecified;
            }
            set
            {
                this.fecha_pago_probableFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 8)]
        public string ndias_apagar_subsidios
        {
            get
            {
                return this.ndias_apagar_subsidiosField;
            }
            set
            {
                this.ndias_apagar_subsidiosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 9)]
        public string ndias_apagar_prevision
        {
            get
            {
                return this.ndias_apagar_previsionField;
            }
            set
            {
                this.ndias_apagar_previsionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEVerPronunciamientoResponse
    {

        private string estadoField;

        private string gloEstadoField;

        private string idLicenciaField;

        private string dvLicenciaField;

        private string n_resolucionField;

        private string rutTrabajadorField;

        private string digTrabajadorField;

        private System.DateTime fechaEmisionField;

        private System.DateTime fechaInicioReposoField;

        private string diasLicenciaField;

        private string tipoLmeResueltaField;

        private string diasAutorizadosField;

        private System.DateTime fecAutDesdeField;

        private bool fecAutDesdeFieldSpecified;

        private System.DateTime fecAutHastaField;

        private bool fecAutHastaFieldSpecified;

        private System.DateTime fecResolucionField;

        private bool fecResolucionFieldSpecified;

        private string tipoResolucionField;

        private string derechoSubsidioField;

        private string codigo_causa_rechazoField;

        private string codigo_continuacionField;

        private LiquidacionType[] listaLiquidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 0)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string GloEstado
        {
            get
            {
                return this.gloEstadoField;
            }
            set
            {
                this.gloEstadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 2)]
        public string IdLicencia
        {
            get
            {
                return this.idLicenciaField;
            }
            set
            {
                this.idLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string DvLicencia
        {
            get
            {
                return this.dvLicenciaField;
            }
            set
            {
                this.dvLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string n_resolucion
        {
            get
            {
                return this.n_resolucionField;
            }
            set
            {
                this.n_resolucionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 5)]
        public string RutTrabajador
        {
            get
            {
                return this.rutTrabajadorField;
            }
            set
            {
                this.rutTrabajadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string DigTrabajador
        {
            get
            {
                return this.digTrabajadorField;
            }
            set
            {
                this.digTrabajadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public System.DateTime FechaEmision
        {
            get
            {
                return this.fechaEmisionField;
            }
            set
            {
                this.fechaEmisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public System.DateTime FechaInicioReposo
        {
            get
            {
                return this.fechaInicioReposoField;
            }
            set
            {
                this.fechaInicioReposoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 9)]
        public string DiasLicencia
        {
            get
            {
                return this.diasLicenciaField;
            }
            set
            {
                this.diasLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 10)]
        public string TipoLmeResuelta
        {
            get
            {
                return this.tipoLmeResueltaField;
            }
            set
            {
                this.tipoLmeResueltaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 11)]
        public string DiasAutorizados
        {
            get
            {
                return this.diasAutorizadosField;
            }
            set
            {
                this.diasAutorizadosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public System.DateTime FecAutDesde
        {
            get
            {
                return this.fecAutDesdeField;
            }
            set
            {
                this.fecAutDesdeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FecAutDesdeSpecified
        {
            get
            {
                return this.fecAutDesdeFieldSpecified;
            }
            set
            {
                this.fecAutDesdeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public System.DateTime FecAutHasta
        {
            get
            {
                return this.fecAutHastaField;
            }
            set
            {
                this.fecAutHastaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FecAutHastaSpecified
        {
            get
            {
                return this.fecAutHastaFieldSpecified;
            }
            set
            {
                this.fecAutHastaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public System.DateTime FecResolucion
        {
            get
            {
                return this.fecResolucionField;
            }
            set
            {
                this.fecResolucionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FecResolucionSpecified
        {
            get
            {
                return this.fecResolucionFieldSpecified;
            }
            set
            {
                this.fecResolucionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 15)]
        public string TipoResolucion
        {
            get
            {
                return this.tipoResolucionField;
            }
            set
            {
                this.tipoResolucionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string DerechoSubsidio
        {
            get
            {
                return this.derechoSubsidioField;
            }
            set
            {
                this.derechoSubsidioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 17)]
        public string codigo_causa_rechazo
        {
            get
            {
                return this.codigo_causa_rechazoField;
            }
            set
            {
                this.codigo_causa_rechazoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 18)]
        public string codigo_continuacion
        {
            get
            {
                return this.codigo_continuacionField;
            }
            set
            {
                this.codigo_continuacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LiquidacionType[] ListaLiquid
        {
            get
            {
                return this.listaLiquidField;
            }
            set
            {
                this.listaLiquidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEVerPronunciamiento
    {

        private string codigoOperadorField;

        private string rutEmpleadorField;

        private string dvEmpleadorField;

        private string idUnidadrrhhField;

        private string claveField;

        private string tipoFormularioField;

        private string idLicenciaField;

        private string dvLicenciaField;

        private System.DateTime fechaConsultaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CodigoOperador
        {
            get
            {
                return this.codigoOperadorField;
            }
            set
            {
                this.codigoOperadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 1)]
        public string RutEmpleador
        {
            get
            {
                return this.rutEmpleadorField;
            }
            set
            {
                this.rutEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string DvEmpleador
        {
            get
            {
                return this.dvEmpleadorField;
            }
            set
            {
                this.dvEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string IdUnidadrrhh
        {
            get
            {
                return this.idUnidadrrhhField;
            }
            set
            {
                this.idUnidadrrhhField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string TipoFormulario
        {
            get
            {
                return this.tipoFormularioField;
            }
            set
            {
                this.tipoFormularioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 6)]
        public string IdLicencia
        {
            get
            {
                return this.idLicenciaField;
            }
            set
            {
                this.idLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string DvLicencia
        {
            get
            {
                return this.dvLicenciaField;
            }
            set
            {
                this.dvLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public System.DateTime FechaConsulta
        {
            get
            {
                return this.fechaConsultaField;
            }
            set
            {
                this.fechaConsultaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEInfAdjuntoResponse
    {

        private string estadoField;

        private string gloEstadoField;

        private string direccionAdjuntoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 0)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string GloEstado
        {
            get
            {
                return this.gloEstadoField;
            }
            set
            {
                this.gloEstadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string DireccionAdjunto
        {
            get
            {
                return this.direccionAdjuntoField;
            }
            set
            {
                this.direccionAdjuntoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEInfAdjunto
    {

        private string codigoOperadorField;

        private string rutEmpleadorField;

        private string dvEmpleadorField;

        private string idUnidadrrhhField;

        private string claveField;

        private System.DateTime fechaOperacionField;

        private string idLicenciaField;

        private string dvLicenciaField;

        private string nombreArchivoField;

        private string tipoArchivoField;

        private byte[] dataArchivoField;

        private string urlArchivoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CodigoOperador
        {
            get
            {
                return this.codigoOperadorField;
            }
            set
            {
                this.codigoOperadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 1)]
        public string RutEmpleador
        {
            get
            {
                return this.rutEmpleadorField;
            }
            set
            {
                this.rutEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string DvEmpleador
        {
            get
            {
                return this.dvEmpleadorField;
            }
            set
            {
                this.dvEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string IdUnidadrrhh
        {
            get
            {
                return this.idUnidadrrhhField;
            }
            set
            {
                this.idUnidadrrhhField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public System.DateTime FechaOperacion
        {
            get
            {
                return this.fechaOperacionField;
            }
            set
            {
                this.fechaOperacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 6)]
        public string IdLicencia
        {
            get
            {
                return this.idLicenciaField;
            }
            set
            {
                this.idLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string DvLicencia
        {
            get
            {
                return this.dvLicenciaField;
            }
            set
            {
                this.dvLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string NombreArchivo
        {
            get
            {
                return this.nombreArchivoField;
            }
            set
            {
                this.nombreArchivoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 9)]
        public string TipoArchivo
        {
            get
            {
                return this.tipoArchivoField;
            }
            set
            {
                this.tipoArchivoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 10)]
        public byte[] DataArchivo
        {
            get
            {
                return this.dataArchivoField;
            }
            set
            {
                this.dataArchivoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string UrlArchivo
        {
            get
            {
                return this.urlArchivoField;
            }
            set
            {
                this.urlArchivoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEInfSeccCResponse
    {

        private string estadoField;

        private string gloEstadoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 0)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string GloEstado
        {
            get
            {
                return this.gloEstadoField;
            }
            set
            {
                this.gloEstadoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEInfSeccC
    {

        private string codigoOperadorField;

        private string rutEmpleadorField;

        private string dvEmpleadorField;

        private string idUnidadrrhhField;

        private string claveField;

        private string tipoFormularioField;

        private string idLicenciaField;

        private string dvLicenciaField;

        private System.DateTime fecProcesoField;

        private byte[] datosZonaCField;

        private string motivoNoRecepcionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CodigoOperador
        {
            get
            {
                return this.codigoOperadorField;
            }
            set
            {
                this.codigoOperadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 1)]
        public string RutEmpleador
        {
            get
            {
                return this.rutEmpleadorField;
            }
            set
            {
                this.rutEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string DvEmpleador
        {
            get
            {
                return this.dvEmpleadorField;
            }
            set
            {
                this.dvEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string IdUnidadrrhh
        {
            get
            {
                return this.idUnidadrrhhField;
            }
            set
            {
                this.idUnidadrrhhField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string TipoFormulario
        {
            get
            {
                return this.tipoFormularioField;
            }
            set
            {
                this.tipoFormularioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 6)]
        public string IdLicencia
        {
            get
            {
                return this.idLicenciaField;
            }
            set
            {
                this.idLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string DvLicencia
        {
            get
            {
                return this.dvLicenciaField;
            }
            set
            {
                this.dvLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public System.DateTime FecProceso
        {
            get
            {
                return this.fecProcesoField;
            }
            set
            {
                this.fecProcesoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 9)]
        public byte[] DatosZonaC
        {
            get
            {
                return this.datosZonaCField;
            }
            set
            {
                this.datosZonaCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 10)]
        public string MotivoNoRecepcion
        {
            get
            {
                return this.motivoNoRecepcionField;
            }
            set
            {
                this.motivoNoRecepcionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LicenciaType
    {

        private string numLicenciaField;

        private string digLicenciaField;

        private string estadoField;

        private System.DateTime fechaField;

        private string paternoTrabajadorField;

        private string maternoTrabajadorField;

        private string nombreTrabajadorField;

        private string rutTrabajadorField;

        private string digTrabajadorField;

        private System.DateTime fechaEmisionField;

        private System.DateTime fechaInicioReposoField;

        private string edadField;

        private string sexoField;

        private string diasLicenciaField;

        private string paternoHijoField;

        private string maternoHijoField;

        private string nombreHijoField;

        private string rutHijoField;

        private string digHijoField;

        private System.DateTime fechaNacHijoField;

        private string codigo_tipo_licenciaField;

        private string codigo_trayectoField;

        private string rutProfesionalField;

        private string digProfesionalField;

        private string ap_paterno_profesionalField;

        private string ap_materno_profesionalField;

        private string nombres_profesionalField;

        private string codigo_tipo_reposoField;

        private string codigo_jornada_reposoField;

        private string codigo_lugar_reposoField;

        private string calle_reposoField;

        private string nro_reposoField;

        private string depto_reposoField;

        private string comuna_reposoField;

        private string ciudad_reposoField;

        private string motivo_devolucionField;

        private string codigo_oaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 0)]
        public string NumLicencia
        {
            get
            {
                return this.numLicenciaField;
            }
            set
            {
                this.numLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string DigLicencia
        {
            get
            {
                return this.digLicenciaField;
            }
            set
            {
                this.digLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 2)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public System.DateTime fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string PaternoTrabajador
        {
            get
            {
                return this.paternoTrabajadorField;
            }
            set
            {
                this.paternoTrabajadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string MaternoTrabajador
        {
            get
            {
                return this.maternoTrabajadorField;
            }
            set
            {
                this.maternoTrabajadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string NombreTrabajador
        {
            get
            {
                return this.nombreTrabajadorField;
            }
            set
            {
                this.nombreTrabajadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 7)]
        public string RutTrabajador
        {
            get
            {
                return this.rutTrabajadorField;
            }
            set
            {
                this.rutTrabajadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string DigTrabajador
        {
            get
            {
                return this.digTrabajadorField;
            }
            set
            {
                this.digTrabajadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public System.DateTime FechaEmision
        {
            get
            {
                return this.fechaEmisionField;
            }
            set
            {
                this.fechaEmisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public System.DateTime FechaInicioReposo
        {
            get
            {
                return this.fechaInicioReposoField;
            }
            set
            {
                this.fechaInicioReposoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 11)]
        public string Edad
        {
            get
            {
                return this.edadField;
            }
            set
            {
                this.edadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string Sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 13)]
        public string DiasLicencia
        {
            get
            {
                return this.diasLicenciaField;
            }
            set
            {
                this.diasLicenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string PaternoHijo
        {
            get
            {
                return this.paternoHijoField;
            }
            set
            {
                this.paternoHijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string MaternoHijo
        {
            get
            {
                return this.maternoHijoField;
            }
            set
            {
                this.maternoHijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string NombreHijo
        {
            get
            {
                return this.nombreHijoField;
            }
            set
            {
                this.nombreHijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 17)]
        public string RutHijo
        {
            get
            {
                return this.rutHijoField;
            }
            set
            {
                this.rutHijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public string DigHijo
        {
            get
            {
                return this.digHijoField;
            }
            set
            {
                this.digHijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
        public System.DateTime FechaNacHijo
        {
            get
            {
                return this.fechaNacHijoField;
            }
            set
            {
                this.fechaNacHijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 20)]
        public string codigo_tipo_licencia
        {
            get
            {
                return this.codigo_tipo_licenciaField;
            }
            set
            {
                this.codigo_tipo_licenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 21)]
        public string codigo_trayecto
        {
            get
            {
                return this.codigo_trayectoField;
            }
            set
            {
                this.codigo_trayectoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 22)]
        public string RutProfesional
        {
            get
            {
                return this.rutProfesionalField;
            }
            set
            {
                this.rutProfesionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 23)]
        public string DigProfesional
        {
            get
            {
                return this.digProfesionalField;
            }
            set
            {
                this.digProfesionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 24)]
        public string ap_paterno_profesional
        {
            get
            {
                return this.ap_paterno_profesionalField;
            }
            set
            {
                this.ap_paterno_profesionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 25)]
        public string ap_materno_profesional
        {
            get
            {
                return this.ap_materno_profesionalField;
            }
            set
            {
                this.ap_materno_profesionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 26)]
        public string nombres_profesional
        {
            get
            {
                return this.nombres_profesionalField;
            }
            set
            {
                this.nombres_profesionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 27)]
        public string codigo_tipo_reposo
        {
            get
            {
                return this.codigo_tipo_reposoField;
            }
            set
            {
                this.codigo_tipo_reposoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 28)]
        public string codigo_jornada_reposo
        {
            get
            {
                return this.codigo_jornada_reposoField;
            }
            set
            {
                this.codigo_jornada_reposoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 29)]
        public string codigo_lugar_reposo
        {
            get
            {
                return this.codigo_lugar_reposoField;
            }
            set
            {
                this.codigo_lugar_reposoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 30)]
        public string calle_reposo
        {
            get
            {
                return this.calle_reposoField;
            }
            set
            {
                this.calle_reposoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 31)]
        public string nro_reposo
        {
            get
            {
                return this.nro_reposoField;
            }
            set
            {
                this.nro_reposoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 32)]
        public string depto_reposo
        {
            get
            {
                return this.depto_reposoField;
            }
            set
            {
                this.depto_reposoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 33)]
        public string comuna_reposo
        {
            get
            {
                return this.comuna_reposoField;
            }
            set
            {
                this.comuna_reposoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 34)]
        public string ciudad_reposo
        {
            get
            {
                return this.ciudad_reposoField;
            }
            set
            {
                this.ciudad_reposoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 35)]
        public string motivo_devolucion
        {
            get
            {
                return this.motivo_devolucionField;
            }
            set
            {
                this.motivo_devolucionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 36)]
        public string codigo_oa
        {
            get
            {
                return this.codigo_oaField;
            }
            set
            {
                this.codigo_oaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEEvenLccResponse
    {

        private int estadoField;

        private string gloEstadoField;

        private LicenciaType[] listaEstadosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 0)]
        public int Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string GloEstado
        {
            get
            {
                return this.gloEstadoField;
            }
            set
            {
                this.gloEstadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public LicenciaType[] ListaEstados
        {
            get
            {
                return this.listaEstadosField;
            }
            set
            {
                this.listaEstadosField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEEvenLcc
    {

        private string codigoOperadorField;

        private int rutEmpleadorField;

        private string dvEmpleadorField;

        private string idUnidadrrhhField;

        private string claveField;

        private string tipoFormularioField;

        private System.DateTime fechaDesdeConsultaField;

        private System.DateTime fechaHastaConsultaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CodigoOperador
        {
            get
            {
                return this.codigoOperadorField;
            }
            set
            {
                this.codigoOperadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 1)]
        public int RutEmpleador
        {
            get
            {
                return this.rutEmpleadorField;
            }
            set
            {
                this.rutEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string DvEmpleador
        {
            get
            {
                return this.dvEmpleadorField;
            }
            set
            {
                this.dvEmpleadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string IdUnidadrrhh
        {
            get
            {
                return this.idUnidadrrhhField;
            }
            set
            {
                this.idUnidadrrhhField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string TipoFormulario
        {
            get
            {
                return this.tipoFormularioField;
            }
            set
            {
                this.tipoFormularioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public System.DateTime FechaDesdeConsulta
        {
            get
            {
                return this.fechaDesdeConsultaField;
            }
            set
            {
                this.fechaDesdeConsultaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public System.DateTime FechaHastaConsulta
        {
            get
            {
                return this.fechaHastaConsultaField;
            }
            set
            {
                this.fechaHastaConsultaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:WsLMEEmp")]
    public partial class LMEDetLccZAResponse
    {

        private int estadoField;

        private string gloEstadoField;

        private byte[] dctoLmeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int", Order = 0)]
        public int Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string GloEstado
        {
            get
            {
                return this.gloEstadoField;
            }
            set
            {
                this.gloEstadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 2)]
        public byte[] DctoLme
        {
            get
            {
                return this.dctoLmeField;
            }
            set
            {
                this.dctoLmeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEDetLccZARequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEDetLccZA LMEDetLccZA;

        public LMEDetLccZARequest()
        {
        }

        public LMEDetLccZARequest(Imed.LicenciasMedicas.LMEDetLccZA LMEDetLccZA)
        {
            this.LMEDetLccZA = LMEDetLccZA;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEDetLccZAResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEDetLccZAResponse LMEDetLccZAResponse;

        public LMEDetLccZAResponse1()
        {
        }

        public LMEDetLccZAResponse1(Imed.LicenciasMedicas.LMEDetLccZAResponse LMEDetLccZAResponse)
        {
            this.LMEDetLccZAResponse = LMEDetLccZAResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEEvenLccRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEEvenLcc LMEEvenLcc;

        public LMEEvenLccRequest()
        {
        }

        public LMEEvenLccRequest(Imed.LicenciasMedicas.LMEEvenLcc LMEEvenLcc)
        {
            this.LMEEvenLcc = LMEEvenLcc;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEEvenLccResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEEvenLccResponse LMEEvenLccResponse;

        public LMEEvenLccResponse1()
        {
        }

        public LMEEvenLccResponse1(Imed.LicenciasMedicas.LMEEvenLccResponse LMEEvenLccResponse)
        {
            this.LMEEvenLccResponse = LMEEvenLccResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEInfSeccCRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEInfSeccC LMEInfSeccC;

        public LMEInfSeccCRequest()
        {
        }

        public LMEInfSeccCRequest(Imed.LicenciasMedicas.LMEInfSeccC LMEInfSeccC)
        {
            this.LMEInfSeccC = LMEInfSeccC;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEInfSeccCResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEInfSeccCResponse LMEInfSeccCResponse;

        public LMEInfSeccCResponse1()
        {
        }

        public LMEInfSeccCResponse1(Imed.LicenciasMedicas.LMEInfSeccCResponse LMEInfSeccCResponse)
        {
            this.LMEInfSeccCResponse = LMEInfSeccCResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEInfAdjuntoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEInfAdjunto LMEInfAdjunto;

        public LMEInfAdjuntoRequest()
        {
        }

        public LMEInfAdjuntoRequest(Imed.LicenciasMedicas.LMEInfAdjunto LMEInfAdjunto)
        {
            this.LMEInfAdjunto = LMEInfAdjunto;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEInfAdjuntoResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEInfAdjuntoResponse LMEInfAdjuntoResponse;

        public LMEInfAdjuntoResponse1()
        {
        }

        public LMEInfAdjuntoResponse1(Imed.LicenciasMedicas.LMEInfAdjuntoResponse LMEInfAdjuntoResponse)
        {
            this.LMEInfAdjuntoResponse = LMEInfAdjuntoResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEVerPronunciamientoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEVerPronunciamiento LMEVerPronunciamiento;

        public LMEVerPronunciamientoRequest()
        {
        }

        public LMEVerPronunciamientoRequest(Imed.LicenciasMedicas.LMEVerPronunciamiento LMEVerPronunciamiento)
        {
            this.LMEVerPronunciamiento = LMEVerPronunciamiento;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEVerPronunciamientoResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEVerPronunciamientoResponse LMEVerPronunciamientoResponse;

        public LMEVerPronunciamientoResponse1()
        {
        }

        public LMEVerPronunciamientoResponse1(Imed.LicenciasMedicas.LMEVerPronunciamientoResponse LMEVerPronunciamientoResponse)
        {
            this.LMEVerPronunciamientoResponse = LMEVerPronunciamientoResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEEstLccRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEEstLcc LMEEstLcc;

        public LMEEstLccRequest()
        {
        }

        public LMEEstLccRequest(Imed.LicenciasMedicas.LMEEstLcc LMEEstLcc)
        {
            this.LMEEstLcc = LMEEstLcc;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEEstLccResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEEstLccResponse LMEEstLccResponse;

        public LMEEstLccResponse1()
        {
        }

        public LMEEstLccResponse1(Imed.LicenciasMedicas.LMEEstLccResponse LMEEstLccResponse)
        {
            this.LMEEstLccResponse = LMEEstLccResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEDettLccPdfRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEDettLccPdf LMEDettLccPdf;

        public LMEDettLccPdfRequest()
        {
        }

        public LMEDettLccPdfRequest(Imed.LicenciasMedicas.LMEDettLccPdf LMEDettLccPdf)
        {
            this.LMEDettLccPdf = LMEDettLccPdf;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class LMEDettLccPdfResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:WsLMEEmp", Order = 0)]
        public Imed.LicenciasMedicas.LMEDetLccPdfResponse LMEDetLccPdfResponse;

        public LMEDettLccPdfResponse()
        {
        }

        public LMEDettLccPdfResponse(Imed.LicenciasMedicas.LMEDetLccPdfResponse LMEDetLccPdfResponse)
        {
            this.LMEDetLccPdfResponse = LMEDetLccPdfResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WsLMEEmpPortTypeChannel : Imed.LicenciasMedicas.WsLMEEmpPortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WsLMEEmpPortTypeClient : System.ServiceModel.ClientBase<Imed.LicenciasMedicas.WsLMEEmpPortType>, Imed.LicenciasMedicas.WsLMEEmpPortType
    {

        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public WsLMEEmpPortTypeClient() :
                base(WsLMEEmpPortTypeClient.GetDefaultBinding(), WsLMEEmpPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WsLMEEmpSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WsLMEEmpPortTypeClient(EndpointConfiguration endpointConfiguration) :
                base(WsLMEEmpPortTypeClient.GetBindingForEndpoint(endpointConfiguration), WsLMEEmpPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WsLMEEmpPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(WsLMEEmpPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WsLMEEmpPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(WsLMEEmpPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public WsLMEEmpPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEDetLccZAResponse1> Imed.LicenciasMedicas.WsLMEEmpPortType.LMEDetLccZAAsync(Imed.LicenciasMedicas.LMEDetLccZARequest request)
        {
            return base.Channel.LMEDetLccZAAsync(request);
        }

        public System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEDetLccZAResponse1> LMEDetLccZAAsync(Imed.LicenciasMedicas.LMEDetLccZA LMEDetLccZA)
        {
            Imed.LicenciasMedicas.LMEDetLccZARequest inValue = new Imed.LicenciasMedicas.LMEDetLccZARequest();
            inValue.LMEDetLccZA = LMEDetLccZA;
            return ((Imed.LicenciasMedicas.WsLMEEmpPortType)(this)).LMEDetLccZAAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEEvenLccResponse1> Imed.LicenciasMedicas.WsLMEEmpPortType.LMEEvenLccAsync(Imed.LicenciasMedicas.LMEEvenLccRequest request)
        {
            return base.Channel.LMEEvenLccAsync(request);
        }

        public System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEEvenLccResponse1> LMEEvenLccAsync(Imed.LicenciasMedicas.LMEEvenLcc LMEEvenLcc)
        {
            Imed.LicenciasMedicas.LMEEvenLccRequest inValue = new Imed.LicenciasMedicas.LMEEvenLccRequest();
            inValue.LMEEvenLcc = LMEEvenLcc;
            return ((Imed.LicenciasMedicas.WsLMEEmpPortType)(this)).LMEEvenLccAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEInfSeccCResponse1> Imed.LicenciasMedicas.WsLMEEmpPortType.LMEInfSeccCAsync(Imed.LicenciasMedicas.LMEInfSeccCRequest request)
        {
            return base.Channel.LMEInfSeccCAsync(request);
        }

        public System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEInfSeccCResponse1> LMEInfSeccCAsync(Imed.LicenciasMedicas.LMEInfSeccC LMEInfSeccC)
        {
            Imed.LicenciasMedicas.LMEInfSeccCRequest inValue = new Imed.LicenciasMedicas.LMEInfSeccCRequest();
            inValue.LMEInfSeccC = LMEInfSeccC;
            return ((Imed.LicenciasMedicas.WsLMEEmpPortType)(this)).LMEInfSeccCAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEInfAdjuntoResponse1> Imed.LicenciasMedicas.WsLMEEmpPortType.LMEInfAdjuntoAsync(Imed.LicenciasMedicas.LMEInfAdjuntoRequest request)
        {
            return base.Channel.LMEInfAdjuntoAsync(request);
        }

        public System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEInfAdjuntoResponse1> LMEInfAdjuntoAsync(Imed.LicenciasMedicas.LMEInfAdjunto LMEInfAdjunto)
        {
            Imed.LicenciasMedicas.LMEInfAdjuntoRequest inValue = new Imed.LicenciasMedicas.LMEInfAdjuntoRequest();
            inValue.LMEInfAdjunto = LMEInfAdjunto;
            return ((Imed.LicenciasMedicas.WsLMEEmpPortType)(this)).LMEInfAdjuntoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEVerPronunciamientoResponse1> Imed.LicenciasMedicas.WsLMEEmpPortType.LMEVerPronunciamientoAsync(Imed.LicenciasMedicas.LMEVerPronunciamientoRequest request)
        {
            return base.Channel.LMEVerPronunciamientoAsync(request);
        }

        public System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEVerPronunciamientoResponse1> LMEVerPronunciamientoAsync(Imed.LicenciasMedicas.LMEVerPronunciamiento LMEVerPronunciamiento)
        {
            Imed.LicenciasMedicas.LMEVerPronunciamientoRequest inValue = new Imed.LicenciasMedicas.LMEVerPronunciamientoRequest();
            inValue.LMEVerPronunciamiento = LMEVerPronunciamiento;
            return ((Imed.LicenciasMedicas.WsLMEEmpPortType)(this)).LMEVerPronunciamientoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEEstLccResponse1> Imed.LicenciasMedicas.WsLMEEmpPortType.LMEEstLccAsync(Imed.LicenciasMedicas.LMEEstLccRequest request)
        {
            return base.Channel.LMEEstLccAsync(request);
        }

        public System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEEstLccResponse1> LMEEstLccAsync(Imed.LicenciasMedicas.LMEEstLcc LMEEstLcc)
        {
            Imed.LicenciasMedicas.LMEEstLccRequest inValue = new Imed.LicenciasMedicas.LMEEstLccRequest();
            inValue.LMEEstLcc = LMEEstLcc;
            return ((Imed.LicenciasMedicas.WsLMEEmpPortType)(this)).LMEEstLccAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEDettLccPdfResponse> Imed.LicenciasMedicas.WsLMEEmpPortType.LMEDettLccPdfAsync(Imed.LicenciasMedicas.LMEDettLccPdfRequest request)
        {
            return base.Channel.LMEDettLccPdfAsync(request);
        }

        public System.Threading.Tasks.Task<Imed.LicenciasMedicas.LMEDettLccPdfResponse> LMEDettLccPdfAsync(Imed.LicenciasMedicas.LMEDettLccPdf LMEDettLccPdf)
        {
            Imed.LicenciasMedicas.LMEDettLccPdfRequest inValue = new Imed.LicenciasMedicas.LMEDettLccPdfRequest();
            inValue.LMEDettLccPdf = LMEDettLccPdf;
            return ((Imed.LicenciasMedicas.WsLMEEmpPortType)(this)).LMEDettLccPdfAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsLMEEmpSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsLMEEmpSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://wspre.licencia.cl/WsempsWSI.php");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WsLMEEmpPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.WsLMEEmpSOAP);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WsLMEEmpPortTypeClient.GetEndpointAddress(EndpointConfiguration.WsLMEEmpSOAP);
        }

        public enum EndpointConfiguration
        {

            WsLMEEmpSOAP,
        }
    }
}
